CREATE DATABASE Exercicio_1_2;

USE Exercicio_1_2;

CREATE TABLE Cliente
(
	IdCliente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(32) NOT NULL,
	Cpf VARCHAR(11) NOT NULL UNIQUE,
);

CREATE TABLE Empresa
(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(32) NOT NULL,
);

CREATE TABLE Marca 
(
	IdMarca INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(32) NOT NULL UNIQUE,
);

CREATE TABLE Modelo
(
	IdModelo INT PRIMARY KEY IDENTITY,
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca) NOT NULL UNIQUE,
	Nome VARCHAR(64) NOT NULL UNIQUE,
);

CREATE TABLE Veiculo
(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa) NOT NULL UNIQUE,
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo) NOT NULL UNIQUE,
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca) NOT NULL UNIQUE,
	Placa VARCHAR(7) NOT NULL,
);

CREATE TABLE Aluguel
(
	IdAluguel INT PRIMARY KEY IDENTITY,
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo(IdVeiculo) NOT NULL UNIQUE,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente) NOT NULL UNIQUE,
	Inicio VARCHAR(10) NOT NULL,
	Fim VARCHAR(10) NOT NULL,
);