CREATE DATABASE Exercicio_1_3;

USE Exercicio_1_3;

CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	Endereco VARCHAR(128) NOT NULL,
);

CREATE TABLE TipoPet
(
	IdTipoPet INT PRIMARY KEY IDENTITY,
	Descricao VARCHAR(128) NOT NULL,
);

CREATE TABLE Raca
(
	IdRaca INT PRIMARY KEY IDENTITY,
	IdTipoPet INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet) NOT NULL, 
	Descricao VARCHAR(128) NOT NULL,
);

CREATE TABLE Dono
(
	IdDono INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(32) NOT NULL,
);

CREATE TABLE Veterinario
(
	IdVeterinario INT PRIMARY KEY IDENTITY,
	IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica) NOT NULL UNIQUE,
	Nome VARCHAR(32) NOT NULL,
);

CREATE TABLE Pet
(
	IdPet INT PRIMARY KEY IDENTITY,
	IdTipoPet INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet) NOT NULL UNIQUE,
	IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca) NOT NULL UNIQUE,
	IdDono INT FOREIGN KEY REFERENCES Dono(IdDono) NOT NULL UNIQUE,
	Nome VARCHAR(32) NOT NULL,
	DataNascimento VARCHAR(10) NOT NULL,
);

CREATE TABLE Atendimento
(
	IdAtendimento INT PRIMARY KEY IDENTITY,
	IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario) NOT NULL,
	IdPet INT FOREIGN KEY REFERENCES Pet(IdPet) NOT NULL,
	Descricao VARCHAR(128) NOT NULL,
	DataA VARCHAR(10) NOT NULL,
);