-- DDL - DATA DEFINITION LANGUAGE

-- criar o banco de dados
CREATE DATABASE [Event+_Tarde]
USE [Event+_Tarde]

-- criar as tabelas
CREATE TABLE TiposDeUsuario
(
	IdTipoDeUsuario INT PRIMARY KEY IDENTITY,
	NomeTipoDeUsuario VARCHAR(50) NOT NULL,
);

CREATE TABLE TiposDeEvento
(
	IdTipoDeEvento INT PRIMARY KEY IDENTITY,
	NomeTipoDeEvento VARCHAR(50) NOT NULL UNIQUE,
);

CREATE TABLE Instituicao
(
	IdInstituicao INT PRIMARY KEY IDENTITY,
	CNPJ CHAR(14) NOT NULL UNIQUE,
	Endereco VARCHAR(200) NOT NULL,
	NomeFantasia VARCHAR(200) NOT NULL
);

CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdTipoDeUsuario INT FOREIGN KEY REFERENCES TiposDeUsuario(IdTipoDeUsuario) NOT NULL,
	Nome VARCHAR(128) NOT NULL,
	Email VARCHAR(255) NOT NULL UNIQUE,
	Senha VARCHAR(32) NOT NULL,
);

CREATE TABLE Evento
(
	IdEvento INT PRIMARY KEY IDENTITY,
	IdTipoDeEvento INT FOREIGN KEY REFERENCES TiposDeEvento(IdTipoDeEvento) NOT NULL UNIQUE,
	IdInstituicao INT FOREIGN KEY REFERENCES Instituicao(IdInstituicao) NOT NULL UNIQUE,
	Nome VARCHAR(128) NOT NULL,
	Descricao VARCHAR(255) NOT NULL,
	DataEvento DATE NOT NULL,
	HoraEvento TIME NOT NULL,
);

CREATE TABLE PresencasEvento
(
	IdPresencaEvento INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL UNIQUE,
	IdEvento INT FOREIGN KEY REFERENCES Evento(IdEvento) NOT NULL UNIQUE,
	Situacao BIT DEFAULT(0),
);

CREATE TABLE ComentarioEvento
(
	IdComentarioEvento INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL UNIQUE,
	IdEvento INT FOREIGN KEY REFERENCES Evento(IdEvento) NOT NULL UNIQUE,
	DataComentario DATE NOT NULL,
	Descricao VARCHAR(128) NOT NULL,
	Exibe BIT NOT NULL,
);
