--DDL - CRIAR BANCO E TABELAS

--CRIAR UM BANCO
CREATE DATABASE Exercicio_1_1;

--USAR O BANCO CRIADO
USE Exercicio_1_1;

--CRIAR TABELAS
CREATE TABLE Pessoa
(
	IdPessoa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(16) NOT NULL,
	Cnh VARCHAR(10) NOT NULL UNIQUE,
);

CREATE TABLE Telefone
(
	IdTelefone INT PRIMARY KEY IDENTITY,
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa) NOT NULL,
	Numero VARCHAR(16) NOT NULL UNIQUE,
);

CREATE TABLE Email
(
	IdEmail INT PRIMARY KEY IDENTITY,
	IdPessoa INT FOREIGN KEY REFERENCES Pessoa(IdPessoa) NOT NULL,
	Endereco VARCHAR(256) NOT NULL UNIQUE,
);

SELECT * FROM Pessoa;
SELECT * FROM Telefone;
SELECT * FROM Email;