CREATE DATABASE Exercicio_1_5;

USE Exercicio_1_5;

CREATE TABLE Loja 
(
	IdLoja INT PRIMARY KEY IDENTITY,
	NomeFantasia VARCHAR(64) NOT NULL UNIQUE,
);

CREATE TABLE Cliente
(
	IdCliente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(64) NOT NULL,
);

CREATE TABLE Categoria
(
	IdCategoria INT PRIMARY KEY IDENTITY,
	IdLoja INT FOREIGN KEY REFERENCES Loja(IdLoja) NOT NULL,
	Nome VARCHAR(32) NOT NULL,
);

CREATE TABLE Pedido
(
	IdPedido INT PRIMARY KEY IDENTITY,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente) NOT NULL,
	Numero INT NOT NULL UNIQUE,
);

CREATE TABLE Subcategoria
(
	IdSubcategoria INT PRIMARY KEY IDENTITY,
	IdCategoria INT FOREIGN KEY REFERENCES Categoria(IdCategoria) NOT NULL,
	Nome VARCHAR(32) NOT NULL,
);

CREATE TABLE Produto
(
	IdProduto INT PRIMARY KEY IDENTITY,
	IdSubcategoria INT FOREIGN KEY REFERENCES Subcategoria(IdSubcategoria) NOT NULL,
	Nome VARCHAR(64) NOT NULL,
)

CREATE TABLE PedidoProduto
(
	IdPedidoProduto INT PRIMARY KEY IDENTITY,
	IdPedido INT FOREIGN KEY REFERENCES Pedido(IdPedido) NOT NULL,
	IdProduto INT FOREIGN KEY REFERENCES Produto(IdProduto) NOT NULL,
);