-- DDL - DATA DEFINITION LANGUAGE - LINGUAGEM DE DEFINICAO DE DADOS

-- CRIAR BANCO DE DADOS

CREATE DATABASE Health_Clinic_Tarde;

USE Health_Clinic_Tarde;

-- CRIAR AS TABELAS DO BANCO DE DADOS

CREATE TABLE TipoDeUsuario
(
	IdTipoDeUsuario INT PRIMARY KEY IDENTITY,
	NomeTipoDeUsuario VARCHAR(32) NOT NULL UNIQUE,
);

CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdTipoDeUsuario INT FOREIGN KEY REFERENCES TiposDeUsuarios(IdTipoDeUsuario) NOT NULL,
	NomeUsuario VARCHAR(64) NOT NULL,
	Email VARCHAR(255) NOT NULL UNIQUE,
	Senha VARCHAR(64) NOT NULL,
);

CREATE TABLE Especialidade
(
	IdEspecialidade INT PRIMARY KEY IDENTITY,
	NomeEspecialidade VARCHAR(64) NOT NULL UNIQUE,
);

CREATE TABLE Clinica
(
	IdClinica INT PRIMARY KEY IDENTITY,
	Endereco VARCHAR(128) NOT NULL UNIQUE,
	Unidade VARCHAR (64) NOT NULL UNIQUE,
	CNPJ VARCHAR(14) NOT NULL UNIQUE,
	HoraAbertura TIME NOT NULL,
	HoraEncerramento TIME NOT NULL,
);

CREATE TABLE Medico
(
	IdMedico INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuarios(IdUsuario) NOT NULL UNIQUE,
	IdEspecialidade INT FOREIGN KEY REFERENCES Especialidades(IdEspecialidade) NOT NULL,
	IdClinica INT FOREIGN KEY REFERENCES Clinicas(IdClinica) NOT NULL,
	CRM VARCHAR(6) NOT NULL,
);

CREATE TABLE Paciente
(
	IdPaciente INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuarios(IdUsuario) NOT NULL UNIQUE,
	DataNascimento DATE NOT NULL,
	Telefone VARCHAR(11) NOT NULL UNIQUE,
	RG VARCHAR(9) NOT NULL UNIQUE,
	CPF VARCHAR(11) NOT NULL UNIQUE,
	CEP VARCHAR(8) NOT NULL,
	Endereco VARCHAR(64) NOT NULL,
);

CREATE TABLE Situacao
(
	IdSituacao INT PRIMARY KEY IDENTITY,
	TituloSituacao VARCHAR(32) NOT NULL UNIQUE,
);

CREATE TABLE Consulta
(
	IdConsulta INT PRIMARY KEY IDENTITY,
	IdMedico INT FOREIGN KEY REFERENCES Medicos(IdMedico) NOT NULL,
	IdPaciente INT FOREIGN KEY REFERENCES Pacientes(IdPaciente) NOT NULL,
	IdClinica INT FOREIGN KEY REFERENCES Clinicas(IdClinica) NOT NULL,
	IdSituacao INT FOREIGN KEY REFERENCES Situacoes(IdSituacao) NOT NULL,
	[Data] DATE NOT NULL,
	Horario TIME NOT NULL,
);

CREATE TABLE Prontuario
(
	IdProntuario INT PRIMARY KEY IDENTITY,
	IdConsulta INT FOREIGN KEY REFERENCES Consultas(IdConsulta) NOT NULL,
	Descricao TEXT NOT NULL,
);

CREATE TABLE Comentario
(
	IdComentario INT PRIMARY KEY IDENTITY,
	IdConsulta INT FOREIGN KEY REFERENCES Consultas(IdConsulta) NOT NULL,
	IdPaciente INT FOREIGN KEY REFERENCES Pacientes(IdPaciente) NOT NULL,
	Descricao VARCHAR(255) NOT NULL,
);